"""empty message

Revision ID: 43b2ab6d4ec0
Revises: 84f3c8a39407
Create Date: 2024-05-24 21:23:31.874180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43b2ab6d4ec0'
down_revision = '84f3c8a39407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('orders_end_hour_key', type_='unique')
        batch_op.drop_constraint('orders_total_key', type_='unique')

    with op.batch_alter_table('product_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('order_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_unique_constraint('orders_total_key', ['total'])
        batch_op.create_unique_constraint('orders_end_hour_key', ['end_hour'])

    # ### end Alembic commands ###
