"""empty message

Revision ID: 47473067a1cc
Revises: 4c2809a3b791
Create Date: 2024-05-24 19:19:02.555634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47473067a1cc'
down_revision = '4c2809a3b791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('begin_hour', sa.String(length=100), nullable=False),
    sa.Column('end_hour', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('end_hour'),
    sa.UniqueConstraint('total')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
